#!/usr/bin/env bash
set -ex

export JAX_TRACEBACK_FILTERING=off

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u run_capsule.py  --input ../data/iGluSnFR_simulations_1 --output ../results/ --caiman True
