#!/usr/bin/env bash
set -ex

# export JAX_TRACEBACK_FILTERING=off

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u run_capsule.py  --input ../data/iGluSnFR_simulations_default/5 --output ../results/ --suite2p True

# Capture input and output from command-line arguments
# input=$1
# output=$2
# pipeline=$3  # The third argument specifies which pipeline to use (caiman or suite2p)

# # Check if the third argument is either 'caiman' or 'suite2p'
# if [ "$pipeline" == "caiman" ]; then
#     # Run CaImAn pipeline
#     echo "Running CaImAn pipeline..."
#     python -u run_capsule.py --input "$input" --output "$output" --caiman True

# elif [ "$pipeline" == "suite2p" ]; then
#     # Run Suite2p pipeline
#     echo "Running Suite2p pipeline..."
#     python -u run_capsule.py --input "$input" --output "$output" --suite2p True

# else
#     echo "Error: Invalid pipeline specified. Use 'caiman' or 'suite2p'."
#     exit 1
fi