#!/usr/bin/env bash
set -ex
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

export CAIMAN_TEMP='../scratch'

# export JAX_TRACEBACK_FILTERING=off

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u run_capsule.py  --input ../data/iGluSnFR_simulations_z_default/1 --output ../results/ --caiman True --caiman_initial_temp True

# python -u run_capsule.py  --input ../data/iGluSnFR_simulations_default/2 --output ../results/ --suite2p True
# input=$1
# output=$2
# pipeline=$3  # The third argument specifies which pipeline to use (caiman or suite2p)
# initial_temp=$4  # The fourth argument specifies the initial temp type (optional)

# # Check if the third argument is either 'caiman' or 'suite2p'
# if [ "$pipeline" == "caiman" ]; then
#     # Run CaImAn pipeline with or without initial temp
#     if [ "$initial_temp" == "jorncorre_initial_temp" ]; then
#         echo "Running CaImAn pipeline with jorncorre_initial_temp..."
#         python -u run_capsule.py --input "$input" --output "$output" --caiman True --jorncorre_initial_temp True
#     elif [ "$initial_temp" == "caiman_initial_temp" ]; then
#         echo "Running CaImAn pipeline with caiman_initial_temp..."
#         python -u run_capsule.py --input "$input" --output "$output" --caiman True --caiman_initial_temp True
#     elif [ -z "$initial_temp" ]; then
#         echo "Running CaImAn pipeline without initial temp..."
#         python -u run_capsule.py --input "$input" --output "$output" --caiman True
#     else
#         echo "Error: Invalid initial temp specified. Use 'jorncorre_initial_temp', 'caiman_initial_temp', or leave it empty."
#         exit 1
#     fi

# elif [ "$pipeline" == "suite2p" ]; then
#     # Run Suite2p pipeline with or without initial temp
#     if [ "$initial_temp" == "jorncorre_initial_temp" ]; then
#         echo "Running Suite2p pipeline with jorncorre_initial_temp..."
#         python -u run_capsule.py --input "$input" --output "$output" --suite2p True --jorncorre_initial_temp True
#     elif [ "$initial_temp" == "caiman_initial_temp" ]; then
#         echo "Running Suite2p pipeline with caiman_initial_temp..."
#         python -u run_capsule.py --input "$input" --output "$output" --suite2p True --caiman_initial_temp True
#     elif [ -z "$initial_temp" ]; then
#         echo "Running Suite2p pipeline without initial temp..."
#         python -u run_capsule.py --input "$input" --output "$output" --suite2p True
#     else
#         echo "Error: Invalid initial temp specified. Use 'jorncorre_initial_temp', 'caiman_initial_temp', or leave it empty."
#         exit 1
#     fi

# else 
#     echo "Error: Invalid pipeline specified. Use 'caiman' or 'suite2p'."
#     exit 1
# fi
